//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRySTALClient.CRySTALWaiter {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodOrder", Namespace="http://schemas.datacontract.org/2004/07/CRySTAL")]
    [System.SerializableAttribute()]
    public partial class FoodOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeliverToTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CRySTALClient.CRySTALWaiter.ItemOrder[] FoodOrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CRySTALClient.CRySTALWaiter.FoodOrder.OrderStatusList orderStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeliverToTable {
            get {
                return this.DeliverToTableField;
            }
            set {
                if ((this.DeliverToTableField.Equals(value) != true)) {
                    this.DeliverToTableField = value;
                    this.RaisePropertyChanged("DeliverToTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CRySTALClient.CRySTALWaiter.ItemOrder[] FoodOrders {
            get {
                return this.FoodOrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodOrdersField, value) != true)) {
                    this.FoodOrdersField = value;
                    this.RaisePropertyChanged("FoodOrders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderComment {
            get {
                return this.OrderCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderCommentField, value) != true)) {
                    this.OrderCommentField = value;
                    this.RaisePropertyChanged("OrderComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                if ((this.orderNumberField.Equals(value) != true)) {
                    this.orderNumberField = value;
                    this.RaisePropertyChanged("orderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CRySTALClient.CRySTALWaiter.FoodOrder.OrderStatusList orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                if ((this.orderStatusField.Equals(value) != true)) {
                    this.orderStatusField = value;
                    this.RaisePropertyChanged("orderStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="FoodOrder.OrderStatusList", Namespace="http://schemas.datacontract.org/2004/07/CRySTAL")]
        public enum OrderStatusList : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            sentToCook = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            readyToDeliver = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            outForDelevering = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            returned = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            orderServed = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            orderCanceled = 5,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemOrder", Namespace="http://schemas.datacontract.org/2004/07/CRySTAL")]
    [System.SerializableAttribute()]
    public partial class ItemOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeliverToPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] OrderModsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeliverToPerson {
            get {
                return this.DeliverToPersonField;
            }
            set {
                if ((this.DeliverToPersonField.Equals(value) != true)) {
                    this.DeliverToPersonField = value;
                    this.RaisePropertyChanged("DeliverToPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderComment {
            get {
                return this.OrderCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderCommentField, value) != true)) {
                    this.OrderCommentField = value;
                    this.RaisePropertyChanged("OrderComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] OrderMods {
            get {
                return this.OrderModsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderModsField, value) != true)) {
                    this.OrderModsField = value;
                    this.RaisePropertyChanged("OrderMods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productID {
            get {
                return this.productIDField;
            }
            set {
                if ((this.productIDField.Equals(value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RejectedOrder", Namespace="http://schemas.datacontract.org/2004/07/CRySTAL")]
    [System.SerializableAttribute()]
    public partial class RejectedOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CRySTALClient.CRySTALWaiter.FoodOrder orderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CRySTALClient.CRySTALWaiter.FoodOrder order {
            get {
                return this.orderField;
            }
            set {
                if ((object.ReferenceEquals(this.orderField, value) != true)) {
                    this.orderField = value;
                    this.RaisePropertyChanged("order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillItem", Namespace="http://schemas.datacontract.org/2004/07/CRySTAL")]
    [System.SerializableAttribute()]
    public partial class BillItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ItemPrice {
            get {
                return this.ItemPriceField;
            }
            set {
                if ((this.ItemPriceField.Equals(value) != true)) {
                    this.ItemPriceField = value;
                    this.RaisePropertyChanged("ItemPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Person {
            get {
                return this.PersonField;
            }
            set {
                if ((this.PersonField.Equals(value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRySTALWaiter.IWaiterService")]
    public interface IWaiterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaiterService/PlaceOrder", ReplyAction="http://tempuri.org/IWaiterService/PlaceOrderResponse")]
        void PlaceOrder(string sessionID, CRySTALClient.CRySTALWaiter.FoodOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaiterService/AddItemToBill", ReplyAction="http://tempuri.org/IWaiterService/AddItemToBillResponse")]
        void AddItemToBill(string sessionID, CRySTALClient.CRySTALWaiter.FoodOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaiterService/GetReturnedOrders", ReplyAction="http://tempuri.org/IWaiterService/GetReturnedOrdersResponse")]
        CRySTALClient.CRySTALWaiter.RejectedOrder[] GetReturnedOrders(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaiterService/GetCurrentTables", ReplyAction="http://tempuri.org/IWaiterService/GetCurrentTablesResponse")]
        int[] GetCurrentTables(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaiterService/GetInPaymentTables", ReplyAction="http://tempuri.org/IWaiterService/GetInPaymentTablesResponse")]
        int[] GetInPaymentTables(string sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaiterService/MarkPaid", ReplyAction="http://tempuri.org/IWaiterService/MarkPaidResponse")]
        void MarkPaid(string sessionID, int tblNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWaiterService/GetReceipt", ReplyAction="http://tempuri.org/IWaiterService/GetReceiptResponse")]
        CRySTALClient.CRySTALWaiter.BillItem[] GetReceipt(string sessionID, int tblNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWaiterServiceChannel : CRySTALClient.CRySTALWaiter.IWaiterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WaiterServiceClient : System.ServiceModel.ClientBase<CRySTALClient.CRySTALWaiter.IWaiterService>, CRySTALClient.CRySTALWaiter.IWaiterService {
        
        public WaiterServiceClient() {
        }
        
        public WaiterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WaiterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaiterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WaiterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PlaceOrder(string sessionID, CRySTALClient.CRySTALWaiter.FoodOrder order) {
            base.Channel.PlaceOrder(sessionID, order);
        }
        
        public void AddItemToBill(string sessionID, CRySTALClient.CRySTALWaiter.FoodOrder order) {
            base.Channel.AddItemToBill(sessionID, order);
        }
        
        public CRySTALClient.CRySTALWaiter.RejectedOrder[] GetReturnedOrders(string sessionID) {
            return base.Channel.GetReturnedOrders(sessionID);
        }
        
        public int[] GetCurrentTables(string sessionID) {
            return base.Channel.GetCurrentTables(sessionID);
        }
        
        public int[] GetInPaymentTables(string sessionID) {
            return base.Channel.GetInPaymentTables(sessionID);
        }
        
        public void MarkPaid(string sessionID, int tblNumber) {
            base.Channel.MarkPaid(sessionID, tblNumber);
        }
        
        public CRySTALClient.CRySTALWaiter.BillItem[] GetReceipt(string sessionID, int tblNumber) {
            return base.Channel.GetReceipt(sessionID, tblNumber);
        }
    }
}
